site_name: Panther
theme:
  name: material
  font:
    text: B Nazanin
  palette:
  - scheme: default
    primary: purple
    accent: amber
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - scheme: slate
    primary: purple
    accent: amber
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
#  logo: https://panther.dev/static/images/logo.svg
#  favicon: https://panther.dev/static/images/logo.svg
  language: en

nav:
- Introduction: index.md
- Features: features.md
- Benchmarks: benchmarks.md
- Release Notes: release_notes.md

markdown_extensions:
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format ''
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- mdx_include:
    base_path: docs
- pymdownx.tabbed:
    alternate_style: true
extra_css:
- https://fastapi.tiangolo.com/css/termynal.css
- https://fastapi.tiangolo.com/css/custom.css
extra_javascript:
- https://fastapi.tiangolo.com/js/termynal.js
- https://fastapi.tiangolo.com/js/custom.js